# Generated by Django 4.1 on 2022-09-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_cursos', '0003_posteo_delete_curso_delete_entregable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='imagen',
        ),
    ]
