# Generated by Django 4.1 on 2022-09-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_cursos', '0004_remove_posteo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
