# Generated by Django 4.1 on 2022-09-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_cursos', '0005_posteo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
