# Generated by Django 4.1 on 2022-09-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_cursos', '0006_alter_posteo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
