# Generated by Django 4.1 on 2022-09-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_cursos', '0007_alter_posteo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='ciudad',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posteo',
            name='pais',
            field=models.CharField(default=' ', max_length=40),
            preserve_default=False,
        ),
    ]
